# Generated by Django 2.0.3 on 2018-04-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35, unique=True)),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoDeBaloncesto',
            fields=[
                ('equipo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipo.Equipo')),
                ('posicion', models.IntegerField(default=0)),
                ('partJug', models.IntegerField(default=0)),
                ('partGan', models.IntegerField(default=0)),
                ('partPerd', models.IntegerField(default=0)),
                ('partW', models.IntegerField(default=0)),
                ('cestAfa', models.IntegerField(default=0)),
                ('cestCon', models.IntegerField(default=0)),
                ('cestDif', models.IntegerField(default=0)),
            ],
            bases=('equipo.equipo',),
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torneo.Torneo'),
        ),
    ]
